Repository DjangoBookMakers/SkillBridge, pull requests merged in 2025-03, with the labels that each got.

#2 📝 DOCS: ERD 및 PRD 추가
  docs/ERD.md
  docs/ERD.png
  docs/PRD.md
Labels: documentation

#5 ✨ 로그인/회원가입 기능 및 UI 개선
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  accounts/urls.py
  accounts/views.py
  config/urls.py
  templates/base.html
Labels: enhancement

#9 🛠️ 로그인/회원가입 UI 및 인증 흐름 개선
  accounts/views.py
  templates/base.html
Labels: bug

#17 ♻️ REFACTOR: base.html 파일 분할
  templates/base.html
  templates/footer.html
  templates/home_intro.html
  templates/navbar.html
Labels: enhancement

#21 ♻️ REFACTOR: course_detail.html 파일 분할
  courses/templates/courses/course_detail.html
  courses/templates/courses/course_detail/curriculum.html
  courses/templates/courses/course_detail/header.html
  courses/templates/courses/course_detail/info.html
  courses/templates/courses/course_detail/reviews.html
  courses/templates/courses/course_detail/tab_nav.html
Labels: refactor

#23 🐛 FIX: 메인 로고 클릭시 메인 과정 목록 화면으로 이동
  config/urls.py
  templates/navbar.html
Labels: bug

#24 ✨ feat: 로그인 및 회원가입 페이지 디자인 개선 및 소셜 로그인 구현
  accounts/forms.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/signup.html
  config/settings.py
  config/urls.py
  pdm.lock
  pyproject.toml
  templates/navbar.html
Labels: enhancement

#26 ✨ FEAT: learning 앱 추가
  config/settings.py
  learning/__init__.py
  learning/admin.py
  learning/apps.py
  learning/migrations/__init__.py
  learning/models.py
  learning/tests.py
  learning/urls.py
  learning/views.py
Labels: enhancement

#35 ✨ Feat: 사용자 정보 및 관리 화면 구현
  accounts/forms.py
  accounts/templates/accounts/profile.html
  accounts/templates/accounts/profile_edit.html
  accounts/urls.py
  accounts/views.py
  templates/navbar.html
Labels: enhancement

#36 ✨ feat: 비밀번호 변경 기능 구현
  accounts/forms.py
  accounts/templates/accounts/change_password.html
  accounts/templates/accounts/profile.html
  accounts/urls.py
  accounts/views.py
Labels: enhancement

#44 ✨ FEAT: 과정상세화면에서 과정 수강 중인 경우 이어서 학습하기 기능 구현
  courses/views.py
Labels: enhancement

#46 🚀 사용자 대시보드 기능 구현 및 UI 버그 수정
  accounts/templates/accounts/profile.html
  learning/urls.py
  learning/views.py
  media/profiles/profile_google_1_atLiRJA.jpg
  templates/navbar.html
Labels: bug, enhancement

#48 🐛 FIX: 과정상세화면의 이어서 학습하기 버튼의 이동 위치 수정
  courses/templates/courses/course_detail/header.html
Labels: bug

#50 🛒 사용자 프로필 페이지에 구매 내역 탭 추가
  accounts/templates/accounts/profile.html
  accounts/views.py
Labels: enhancement

#55 🐛 FIX: 과정 상세화면에서 navbar 동작 오류 수정
  courses/templates/courses/course_detail/tab_nav.html
Labels: bug

#61 ✨ FEAT: 어드민 대시보드의 프로젝트제출 조회 및 평가 기능 구현
  admin_portal/templates/admin_portal/dashboard_components/project_table.html
  admin_portal/templates/admin_portal/evaluate_project.html
  admin_portal/templates/admin_portal/pending_projects.html
  admin_portal/templates/admin_portal/project_detail.html
  admin_portal/urls.py
  admin_portal/views.py
  learning/templates/learning/submit_project.html
Labels: enhancement

#64 ✨ FEAT: 관리자 대시보드 동영상 조회 수 표시
  admin_portal/templates/admin_portal/dashboard.html
  admin_portal/templates/admin_portal/dashboard_components/stats_card.html
  admin_portal/views.py
Labels: enhancement

#67 ✨ 관리자 대시보드 과정 관리 기능 구현
  admin_portal/templates/admin_portal/course_management/course_create.html
  admin_portal/templates/admin_portal/course_management/course_detail.html
  admin_portal/templates/admin_portal/course_management/course_list.html
  admin_portal/templates/admin_portal/course_management/lecture_create.html
  admin_portal/templates/admin_portal/course_management/lecture_detail.html
  admin_portal/templates/admin_portal/course_management/lecture_list.html
  admin_portal/templates/admin_portal/course_management/subject_create.html
  admin_portal/templates/admin_portal/course_management/subject_detail.html
  admin_portal/templates/admin_portal/course_management/subject_list.html
  admin_portal/templates/admin_portal/dashboard.html
  admin_portal/urls.py
  admin_portal/views.py
  config/settings.py
Labels: enhancement

#71 ✨ FEAT: 어드민 과정관리 기능
  admin_portal/templates/admin_portal/course_management/course_create.html
  admin_portal/templates/admin_portal/course_management/course_detail.html
  admin_portal/templates/admin_portal/course_management/course_list.html
  admin_portal/templates/admin_portal/course_management/lecture_create.html
  admin_portal/templates/admin_portal/course_management/lecture_detail.html
  admin_portal/templates/admin_portal/course_management/lecture_list.html
  admin_portal/templates/admin_portal/course_management/subject_create.html
  admin_portal/templates/admin_portal/course_management/subject_detail.html
  admin_portal/templates/admin_portal/course_management/subject_list.html
  admin_portal/templates/admin_portal/dashboard.html
  admin_portal/urls.py
  admin_portal/views.py
  config/settings.py
Labels: enhancement

#74 🐛 FIX: 과정관리 생성 오류해결
  admin_portal/views.py
Labels: bug, enhancement

#73 🐛 FIX: 출석부PDF의 한글 깨짐 수정 및 테이블 셀 크기 조절
  admin_portal/views.py
  static/fonts/NanumGothic-Regular.ttf
Labels: bug

#78 ✨ FEAT: payments 앱 추가 및 모델 구현
  config/settings.py
  payments/__init__.py
  payments/admin.py
  payments/apps.py
  payments/migrations/0001_initial.py
  payments/migrations/__init__.py
  payments/models.py
  payments/tests.py
  payments/views.py
Labels: enhancement

#83 🐛 Fix: 푸터가 페이지 하단에 고정되도록 flex 레이아웃 적용
  templates/base.html
Labels: bug

#88 🔒 SECRET_KEY를 환경 변수로 이동하여 보안 강화
  config/settings.py
Labels: enhancement

#91 🔧 chore: Django 기본 주석 제거
  accounts/signals.py
  config/settings.py
  config/urls.py
  config/wsgi.py
Labels: enhancement

#94 ✨ FEAT: 관리자 대시보드에서 수강생의 과정 등록 및 취소 기능 구현
  admin_portal/templates/admin_portal/dashboard.html
  admin_portal/templates/admin_portal/manage_enrollment.html
  admin_portal/urls.py
  admin_portal/views.py
Labels: enhancement

#95 🎨 폼 코드에서 스타일 관련 코드 분리
  accounts/forms.py
  accounts/templates/accounts/login.html
  accounts/templates/accounts/profile_edit.html
  accounts/templatetags/__init__.py
  accounts/templatetags/form_utils.py
  learning/forms.py
  learning/templates/learning/submit_project.html
Labels: enhancement

#98 ✨ feat: 동영상 업로드 기능 개선 및 버그 수정
  accounts/templates/accounts/login.html
  accounts/templatetags/custom_filters.py
  admin_portal/templates/admin_portal/course_management/course_create.html
  admin_portal/templates/admin_portal/course_management/course_detail.html
  admin_portal/templates/admin_portal/course_management/course_list.html
  admin_portal/templates/admin_portal/course_management/lecture_create.html
  admin_portal/views.py
  courses/migrations/0003_rename_video_url_lecture_video_file.py
  courses/models.py
  learning/templates/learning/video_lecture.html
Labels: bug, enhancement

#99 🗃️ FIX: 여러 모델 필드에 대해 DB index 추가
  accounts/migrations/0002_alter_user_is_admin_alter_user_login_at_and_more.py
  accounts/models.py
  courses/migrations/0004_alter_course_created_at_and_more.py
  courses/models.py
  learning/migrations/0002_alter_certificate_certificate_number_and_more.py
  learning/models.py
  payments/migrations/0004_alter_payment_created_at_alter_payment_imp_uid_and_more.py
  payments/models.py
Labels: enhancement

#101 🔧 CHORE: settings.py 파일 분할 및 settings 디렉터리 생성
  config/settings/__init__.py
  config/settings/base.py
  config/settings/dev.py
  config/settings/prod.py
Labels: refactor

#103 🐛 fix: 미션 강의 표시 오류 해결
  admin_portal/templates/admin_portal/course_management/lecture_create.html
  admin_portal/templates/admin_portal/course_management/lecture_detail.html
  admin_portal/templates/admin_portal/course_management/lecture_list.html
  admin_portal/views.py
Labels: bug

#104 🐛 FIX: 강의 생성 오류 수정
  admin_portal/views.py
Labels: bug

#105 FEAT: 🎨 대시보드 상단 버튼 색상 다양화
  admin_portal/templates/admin_portal/dashboard.html
Labels: enhancement

#112 ✨ Feat: 과정 목록 UI 개선
  admin_portal/templates/admin_portal/course_management/course_create.html
  admin_portal/templates/admin_portal/course_management/course_detail.html
  admin_portal/views.py
  courses/templates/courses/course_list.html
Labels: enhancement

#119 🎨 CHORE: 폼에서 CSS 스타일 코드를 템플릿으로 이동
  accounts/forms.py
  accounts/templates/accounts/change_password.html
  accounts/templates/accounts/signup.html
Labels: bug

#121 📚 FEAT: 과목 유형에 따른 강의 수 및 관리 표시 개선
  admin_portal/templates/admin_portal/course_management/subject_list.html
  admin_portal/views.py
Labels: bug

#131 🖼️ FIX: 썸네일 이미지 업로드 및 표시 문제 수정
  admin_portal/templates/admin_portal/course_management/course_create.html
  admin_portal/templates/admin_portal/course_management/course_detail.html
  admin_portal/templates/admin_portal/course_management/course_list.html
Labels: bug

#133 hotfix: fix pdf download
  learning/templates/learning/view_certificate.html
Labels: bug, enhancement

#136 🐛 FIX: 배포 설정 파일 문법 오류 및 migration 누락 수정
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
Labels: bug

#139 🐛 FIX: Dockerfile의 ENV 위치 수정
  Dockerfile
Labels: bug

#140 ➕ CHORE: postgres 사용을 위한 psycopg2 라이브러리 설치
  pdm.lock
  pyproject.toml
Labels: bug, enhancement

#146 FEAT: 배너 과정 동기화
  courses/views.py
  templates/base.html
Labels: enhancement

#148 🔥 FEAT: 과정 필터링 제거
  courses/templates/courses/course_list.html
Labels: enhancement

#156 ✨ FEAT: 가격 단위 표시 개선
  accounts/templates/accounts/profile.html
  payments/templates/payments/payment_complete.html
  payments/templates/payments/payment_detail.html
  payments/templates/payments/payment_history.html
Labels: enhancement

#158 ✨ FEAT: 탈퇴회원 정보 익명화 저장 및 결제내역 삭제 방지
  accounts/migrations/0003_deleteduserdata.py
  accounts/models.py
  accounts/views.py
  admin_portal/models.py
  admin_portal/templates/admin_portal/payments/payment_detail.html
  admin_portal/views.py
  payments/migrations/0005_payment_anonymized_user_id_payment_is_anonymized_and_more.py
  payments/models.py
  payments/templates/payments/payment_detail.html
  payments/templates/payments/payment_history.html
Labels: bug, enhancement

#166 📝 DOCS: README 업데이트
  README.md
Labels: documentation

#167 📝 DOCS: README에 API 명세 및 디렉터리 구조 작성
  README.md
Labels: documentation

#169 📝 DOCS: README에 Django 프로젝트 아키텍처 설명 추가
  README.md
  docs/deployment-architecture.svg
  docs/project-architecture.svg
Labels: documentation

#170 🐛 FIX: 관리자 대시보드 결제 내역의 완료된 거래 값이 안 나오는 문제 해결
  admin_portal/templates/admin_portal/payments/payment_list.html
  admin_portal/views.py
Labels: bug
